import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { buildAnchorIndex, type AnchorOccurrence } from "./derived/anchors.js";
import { buildStephanusIndex, listGreekDialogues } from "./derived/stephanus.js";
import { getRepoRoot } from "./paths.js";
import {
  fieldValueOrEmpty,
  nestedFieldValueInParent,
  observationYamlBlocks,
} from "./wiki/observation-ledger.js";

export const DEFAULT_ANCHOR_REPORT_THRESHOLD = 3;

export type AnchorReportRow = {
  dialogue: string;
  marker: string;
  startChar: number;
  endChar: number;
  anchorCount: number;
  groupCounts: Record<string, number>;
  acceptedObservations: number;
};

type SourceInterval = {
  startChar: number;
  endChar: number;
};

function readAcceptedIntervals(dialogue: string) {
  const ledgerPath = join(getRepoRoot(), "wiki/observations", `${dialogue}.md`);
  let content = "";
  try {
    content = readFileSync(ledgerPath, "utf8");
  } catch {
    return [];
  }

  const intervals: SourceInterval[] = [];
  for (const block of observationYamlBlocks(content)) {
    const status = fieldValueOrEmpty(block, "review_status") || "unreviewed";
    if (status !== "accepted") continue;

    const startChar = Number(nestedFieldValueInParent(block, "source_ref", "start_char"));
    const endChar = Number(nestedFieldValueInParent(block, "source_ref", "end_char"));
    if (!Number.isInteger(startChar) || !Number.isInteger(endChar) || endChar <= startChar) continue;
    intervals.push({ startChar, endChar });
  }

  return intervals.sort((a, b) => a.startChar - b.startChar || a.endChar - b.endChar);
}

function overlaps(left: SourceInterval, right: SourceInterval) {
  return left.startChar < right.endChar && left.endChar > right.startChar;
}

function occurrencesInRange(occurrences: AnchorOccurrence[], range: SourceInterval) {
  return occurrences.filter((occurrence) => occurrence.startChar >= range.startChar && occurrence.startChar < range.endChar);
}

function groupCounts(occurrences: AnchorOccurrence[]) {
  const counts: Record<string, number> = {};
  for (const occurrence of occurrences) {
    counts[occurrence.group] = (counts[occurrence.group] ?? 0) + 1;
  }
  return Object.fromEntries(Object.entries(counts).sort(([a], [b]) => a.localeCompare(b)));
}

function formatGroupCounts(counts: Record<string, number>) {
  return Object.entries(counts)
    .map(([group, count]) => `${group}=${count}`)
    .join(", ");
}

function reportForDialogue(dialogue: string, minAnchorCount: number): AnchorReportRow[] {
  const stephanus = buildStephanusIndex(dialogue);
  const anchorIndex = buildAnchorIndex(dialogue);
  const acceptedIntervals = readAcceptedIntervals(dialogue);
  const rows: AnchorReportRow[] = [];

  for (const marker of stephanus.markers) {
    const range = { startChar: marker.startChar, endChar: marker.endChar };
    const occurrences = occurrencesInRange(anchorIndex.occurrences, range);
    if (occurrences.length < minAnchorCount) continue;

    const acceptedObservations = acceptedIntervals.filter((interval) => overlaps(interval, range)).length;
    if (acceptedObservations > 0) continue;

    rows.push({
      dialogue,
      marker: marker.marker,
      startChar: marker.startChar,
      endChar: marker.endChar,
      anchorCount: occurrences.length,
      groupCounts: groupCounts(occurrences),
      acceptedObservations,
    });
  }

  return rows;
}

export function buildAnchorsReport({
  dialogue,
  minAnchorCount = DEFAULT_ANCHOR_REPORT_THRESHOLD,
}: { dialogue?: string | undefined; minAnchorCount?: number | undefined } = {}) {
  const dialogues = dialogue ? [dialogue] : listGreekDialogues();
  return dialogues
    .flatMap((entry) => reportForDialogue(entry, minAnchorCount))
    .sort((a, b) => b.anchorCount - a.anchorCount || a.dialogue.localeCompare(b.dialogue) || a.startChar - b.startChar);
}

export function renderAnchorsReportText(report: AnchorReportRow[]) {
  if (report.length === 0) return "(none)";

  return report
    .map(
      (row) =>
        `${row.dialogue} ${row.marker}: anchors=${row.anchorCount} (${formatGroupCounts(row.groupCounts)}) accepted_observations=${row.acceptedObservations}`,
    )
    .join("\n");
}

export function renderAnchorsReportMarkdown(report: AnchorReportRow[]) {
  const rows =
    report.length === 0
      ? ["(none)"]
      : [
          "| dialogue | marker | chars | anchors | groups | accepted observations |",
          "|---|---|---:|---:|---|---:|",
          ...report.map(
            (row) =>
              `| ${row.dialogue} | ${row.marker} | ${row.startChar}-${row.endChar} | ${row.anchorCount} | ${formatGroupCounts(row.groupCounts)} | ${row.acceptedObservations} |`,
          ),
        ];

  return [
    "# Anchor Missing-Features Report",
    "",
    "Generated by `bun run harness anchors --write`.",
    "",
    "```yaml",
    `sections: ${report.length}`,
    `min_anchor_count: ${DEFAULT_ANCHOR_REPORT_THRESHOLD}`,
    "```",
    "",
    ...rows,
    "",
  ].join("\n");
}

export function anchorReportPath() {
  return "derived/plato/anchors/report.md";
}

export function writeAnchorsReport({ dialogue }: { dialogue?: string | undefined } = {}) {
  const report = buildAnchorsReport({ dialogue });
  const path = anchorReportPath();
  const absolutePath = join(getRepoRoot(), path);
  mkdirSync(dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, renderAnchorsReportMarkdown(report), "utf8");
  return { path, report };
}
